import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  // Disercomi

  {
    path: '',
    title: 'DISERCOMI.MENU.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'disercomi/perfil',
    title: 'DISERCOMI.PROFILE.TEXT',
    iconType: 'feather',
    icon: 'trello',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'disercomi/documentos',
    title: 'DISERCOMI.DOCUMENTS.TEXT',
    iconType: 'feather',
    icon: 'trello',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: 'DISERCOMI.REQUESTS.TEXT',
    iconType: 'feather',
    icon: 'home',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'disercomi/solicitudes/realizar',
        title: 'DISERCOMI.REQUESTS.LIST.CARRY-OUT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'disercomi/solicitudes/historial',
        title: 'DISERCOMI.REQUESTS.LIST.RECORD',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'disercomi/solicitudes/reasignar',
        title: 'DISERCOMI.REQUESTS.LIST.REASSIGN',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'DISERCOMI.RATINGS.TEXT',
    iconType: 'feather',
    icon: 'home',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'disercomi/calificaciones/historial',
        title: 'DISERCOMI.RATINGS.LIST.RECORD',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }
    ],
  },
];
